### ISSUE TITLE
[R] License Discussion

### ISSUE THREAD

**Issue by markusnam** [UBC-MDS/fxtrackerR#36]

**Comment by markusnam** [comment]
First of all, I think we may decide whether we will use the same type of licence for our `py` package and `R` package.
Since they are just the same thing in terms of nature, I think using the same type of licence is probably fine.

If all of us agree, we may close the issue here and use the issue on the `py` side for further discussion.
https://github.com/UBC-MDS/fxtracker/issues/76

**Comment by missarah96** [comment]
I agree with @markusnam . Same license can be used for R for the reasons I mentioned in `py` version of our package.

**Comment by markusnam** [comment]
We all agree to use MIT License for both `py` and `R`.
Refer to https://github.com/UBC-MDS/fxtracker/issues/76
